"use client";
/* eslint-disable react-hooks/set-state-in-effect -- API state resolves asynchronously. */

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { Icon } from "@/components/icons";
import { api } from "@/lib/api";
import type { HRDashboard, Role } from "@/lib/types";

const day = (value: string) => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { weekday: "short" });
const checkInTime = (value: string | null) => value ? new Date(value).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) : "—";

function Metric({ name, value, accent }: { name: string; value: number; accent: string }) {
  return <article className="app-card relative overflow-hidden rounded-2xl p-5"><span className={`absolute left-0 top-0 h-full w-1 ${accent}`} /><p className="text-sm font-medium text-[#718198]">{name}</p><p className="mt-2 text-3xl font-bold tracking-tight text-[#10233f]">{value}</p></article>;
}

function Empty({ text }: { text: string }) { return <p className="py-9 text-center text-sm text-[#718198]">{text}</p>; }

export function HRDashboardPage({ role }: { role: Role }) {
  const [data, setData] = useState<HRDashboard | null>(null);
  const [error, setError] = useState("");
  const load = useCallback(async () => { try { setError(""); setData(await api.hrDashboard()); } catch (caught) { setError(caught instanceof Error ? caught.message : "HR dashboard could not be loaded."); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (error) return <section className="rounded-2xl border border-[#f3cbd1] bg-[#fff7f8] p-6 text-[#9e3643]"><p>{error}</p><button onClick={() => void load()} className="focus-ring mt-3 rounded-lg px-2 py-1 font-bold underline">Retry</button></section>;
  if (!data) return <section className="space-y-5"><div className="shimmer h-48 rounded-3xl" /><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <div key={index} className="shimmer h-28 rounded-2xl" />)}</div></section>;
  const maxTrend = Math.max(1, ...data.attendance.trend.flatMap((item) => [item.present, item.late, item.on_leave, item.absent]));
  const summary = [["Total employees", data.kpis.total_employees, "bg-[#0869d8]"], ["Present", data.attendance.present, "bg-[#168460]"], ["Late", data.attendance.late, "bg-[#ff8a00]"], ["On leave", data.attendance.on_leave, "bg-[#1497f2]"], ["Absent", data.attendance.absent, "bg-[#c43d4b]"], ["Active now", data.attendance.working_now, "bg-[#0b1f3a]"]];
  return <div className="space-y-6">
    <section className="relative overflow-hidden rounded-[24px] bg-[#0b1f3a] p-6 text-white shadow-[0_20px_46px_rgba(11,31,58,.2)] sm:p-8"><div className="absolute -right-20 -top-24 h-64 w-64 rounded-full border border-white/10" /><div className="absolute -bottom-20 right-20 h-52 w-52 rounded-full bg-[#1497f2]/25 blur-2xl" /><div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[11px] font-bold tracking-[.18em] text-[#9ed5ff]">HUMAN RESOURCES · LIVE OPERATIONS</p><h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">HR Command Center</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#c6e2fb]">Workforce attendance, live availability, and sales activity across your {data.scope === "company" ? "company" : "authorized team"}.</p></div><div className="flex flex-wrap gap-3"><Link href="/attendance" className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-xl bg-white px-4 text-sm font-bold text-[#0869d8]"><Icon name="clock" className="h-4 w-4" />Attendance</Link><Link href="/employees" className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/25 bg-white/10 px-4 text-sm font-bold text-white"><Icon name="users" className="h-4 w-4" />People</Link></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-6">{summary.map(([name, value, accent]) => <Metric key={String(name)} name={String(name)} value={Number(value)} accent={String(accent)} />)}</section>
    <section className="grid gap-5 xl:grid-cols-[1.4fr_.85fr]"><article className="app-card rounded-2xl p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[11px] font-bold tracking-[.14em] text-[#0869d8]">ATTENDANCE INTELLIGENCE</p><h2 className="mt-1 text-lg font-bold text-[#10233f]">Seven-day attendance trend</h2><p className="mt-1 text-sm text-[#718198]">Recorded attendance and approved leave, not estimates.</p></div><span className="rounded-full bg-[#eaf4ff] px-3 py-1.5 text-xs font-bold text-[#0869d8]">{data.attendance.percentage}% present today</span></div><div className="mt-8 grid h-56 grid-cols-7 items-end gap-2 sm:gap-4">{data.attendance.trend.map((item) => <div key={item.date} className="flex h-full min-w-0 flex-col justify-end"><div className="flex h-[190px] items-end justify-center gap-0.5"><span title={`Present: ${item.present}`} className="w-2 rounded-t bg-[#168460] sm:w-3" style={{ height: `${item.present / maxTrend * 100}%` }} /><span title={`Late: ${item.late}`} className="w-2 rounded-t bg-[#ff8a00] sm:w-3" style={{ height: `${item.late / maxTrend * 100}%` }} /><span title={`Leave: ${item.on_leave}`} className="w-2 rounded-t bg-[#1497f2] sm:w-3" style={{ height: `${item.on_leave / maxTrend * 100}%` }} /><span title={`Absent: ${item.absent}`} className="w-2 rounded-t bg-[#c43d4b] sm:w-3" style={{ height: `${item.absent / maxTrend * 100}%` }} /></div><p className="mt-3 text-center text-xs font-bold text-[#718198]">{day(item.date)}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#60708a]"><span><i className="mr-1.5 inline-block h-2 w-2 rounded bg-[#168460]" />Present</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded bg-[#ff8a00]" />Late</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded bg-[#1497f2]" />On leave</span><span><i className="mr-1.5 inline-block h-2 w-2 rounded bg-[#c43d4b]" />Absent</span></div></article>
      <article className="app-card rounded-2xl p-5 sm:p-6"><p className="text-[11px] font-bold tracking-[.14em] text-[#ff8a00]">WORKFORCE ACTIVITY</p><h2 className="mt-1 text-lg font-bold text-[#10233f]">Who&apos;s active now</h2><p className="mt-1 text-sm text-[#718198]">Today&apos;s employee check-in state.</p><div className="mt-5 space-y-1">{data.workforce_activity.length ? data.workforce_activity.slice(0, 6).map((item) => <Link href={`/employees/${item.employee_id}`} key={item.employee_id} className="focus-ring flex items-center gap-3 rounded-xl px-2 py-2.5 transition hover:bg-[#f8fbff]"><i className={`h-2.5 w-2.5 shrink-0 rounded-full ${item.status === "CHECKED_IN" ? "bg-[#168460]" : item.status === "CHECKED_OUT" ? "bg-[#1497f2]" : "bg-[#bac5d1]"}`} /><span className="min-w-0 flex-1"><strong className="block truncate text-sm text-[#253a59]">{item.employee_name}</strong><small className="mt-0.5 block text-xs text-[#718198]">{item.status === "CHECKED_IN" ? `Checked in ${checkInTime(item.check_in_at)}` : item.status === "CHECKED_OUT" ? "Checked out" : "Not checked in"}</small></span><Icon name="chevron" className="h-4 w-4 text-[#a3afbd]" /></Link>) : <Empty text="No active employees in this workspace." />}</div><Link href="/attendance" className="focus-ring mt-5 inline-flex text-sm font-bold text-[#0869d8]">Review attendance →</Link></article></section>
    <section className="app-card overflow-hidden rounded-2xl"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-[#edf1f6] p-5 sm:p-6"><div><p className="text-[11px] font-bold tracking-[.14em] text-[#0869d8]">EMPLOYEE PERFORMANCE</p><h2 className="mt-1 text-lg font-bold text-[#10233f]">Sales performance leaderboard</h2><p className="mt-1 text-sm text-[#718198]">Ranked by closings, then completed site visits. Attendance is deliberately separate.</p></div><Link href="/employees" className="focus-ring text-sm font-bold text-[#0869d8]">Open people →</Link></div>{data.performance.leaderboard.length ? <div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left"><thead className="bg-[#f8fbff] text-[11px] font-bold uppercase tracking-[.1em] text-[#7a8aa0]"><tr><th className="px-6 py-3">Rank</th><th className="px-4 py-3">Employee</th><th className="px-4 py-3 text-right">Leads</th><th className="px-4 py-3 text-right">Contacted</th><th className="px-4 py-3 text-right">Site visits</th><th className="px-4 py-3 text-right">Closings</th><th className="px-6 py-3 text-right">Conversion</th></tr></thead><tbody className="divide-y divide-[#edf1f6]">{data.performance.leaderboard.map((item, index) => <tr key={item.employee_id} className="transition hover:bg-[#fbfdff]"><td className="px-6 py-4"><span className={`flex h-7 w-7 items-center justify-center rounded-lg text-xs font-bold ${index < 3 ? "bg-[#fff3df] text-[#bc7200]" : "bg-[#f1f4f8] text-[#60708a]"}`}>{index + 1}</span></td><td className="px-4 py-4"><Link href={`/employees/${item.employee_id}`} className="focus-ring font-bold text-[#253a59] hover:text-[#0869d8]">{item.employee_name}</Link></td><td className="px-4 py-4 text-right text-sm font-semibold text-[#405773]">{item.leads_assigned}</td><td className="px-4 py-4 text-right text-sm font-semibold text-[#405773]">{item.leads_contacted}</td><td className="px-4 py-4 text-right text-sm font-bold text-[#0869d8]">{item.site_visits}</td><td className="px-4 py-4 text-right text-sm font-bold text-[#168460]">{item.closings}</td><td className="px-6 py-4 text-right text-sm font-bold text-[#253a59]">{item.conversion_rate}%</td></tr>)}</tbody></table></div> : <Empty text="No employee performance data is available yet." />}</section>
    <section className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><article className="app-card rounded-2xl p-5 sm:p-6"><p className="text-[11px] font-bold tracking-[.14em] text-[#0869d8]">WORKFORCE DISTRIBUTION</p><h2 className="mt-1 text-lg font-bold text-[#10233f]">Teams and departments</h2><div className="mt-5 space-y-4">{data.distribution.departments.length ? data.distribution.departments.map((item) => <div key={item.department__name}><div className="flex justify-between gap-3 text-sm"><span className="truncate font-medium text-[#526984]">{item.department__name}</span><strong>{item.count}</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-[#edf1f6]"><div className="h-full rounded-full bg-[#0869d8]" style={{ width: `${item.count / Math.max(1, ...data.distribution.departments.map((entry) => entry.count)) * 100}%` }} /></div></div>) : <Empty text="No department data yet." />}</div></article><article className="app-card overflow-hidden rounded-2xl"><div className="border-b border-[#edf1f6] p-5 sm:p-6"><p className="text-[11px] font-bold tracking-[.14em] text-[#ff8a00]">RECENT ACTIVITY</p><h2 className="mt-1 text-lg font-bold text-[#10233f]">HR activity stream</h2></div>{data.activity.length ? <div className="divide-y divide-[#edf1f6]">{data.activity.slice(0, 5).map((item) => <div key={item.id} className="flex gap-3 p-4 sm:px-6"><span className="mt-1 flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-[#eaf4ff] text-[#0869d8]"><Icon name="sparkle" className="h-3.5 w-3.5" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-[#253a59]">{item.action.replaceAll(".", " ")}</p><p className="mt-1 text-xs text-[#718198]">{item.actor}{item.reason ? ` · ${item.reason}` : ""}</p></div><time className="whitespace-nowrap text-[11px] text-[#8a98aa]">{new Date(item.created_at).toLocaleDateString()}</time></div>)}</div> : <Empty text="No recent HR activity." />}</article></section>
    {role === "CEO" && <p className="px-1 text-xs text-[#718198]">All workforce and performance metrics are scoped to your company.</p>}
  </div>;
}
