# Generated by Django 5.2.17 on 2026-09-24 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepolicy',
            name='workday_end',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
        migrations.AlterField(
            model_name='attendancepolicy',
            name='workday_start',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
