# Generated by Django 5.2.17 on 2026-09-26 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_employeeprofile_can_receive_leads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('normalized_phone', models.CharField(blank=True, max_length=32)),
                ('alternate_phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('preferred_location', models.CharField(blank=True, max_length=255)),
                ('budget_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bhk', models.CharField(blank=True, max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('requirement_notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('META_LEAD_AD', 'Meta lead ad'), ('WEBSITE', 'Website'), ('MANUAL', 'Manual'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], default='MANUAL', max_length=20)),
                ('source_details', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT_REQUESTED', 'Site visit requested'), ('SITE_VISIT_DONE', 'Site visit done'), ('FOLLOW_UP_NEEDED', 'Follow-up needed'), ('FOLLOW_UP_DONE', 'Follow-up done'), ('POSTPONED', 'Postponed'), ('DIFFERENT_REQUIREMENT', 'Different requirement'), ('NOT_INTERESTED', 'Not interested'), ('CLOSED', 'Closed'), ('INVALID_PHONE', 'Invalid phone'), ('NOT_LOOKING_PROPERTY', 'Not looking for property'), ('USER_IS_AGENT', 'User is agent')], default='NEW', max_length=32)),
                ('temperature', models.CharField(choices=[('HOT', 'Hot'), ('WARM', 'Warm'), ('COLD', 'Cold')], default='WARM', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to='organizations.employeeprofile')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('CREATED', 'Lead created'), ('SOURCE_RECEIVED', 'Source received'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('STATUS_CHANGED', 'Status changed'), ('TEMPERATURE_CHANGED', 'Temperature changed'), ('FIELD_CHANGED', 'Field changed'), ('NOTE_ADDED', 'Note added'), ('FOLLOW_UP_CREATED', 'Follow-up created'), ('TASK_CREATED', 'Task created'), ('ARCHIVED', 'Archived')], max_length=24)),
                ('field_name', models.CharField(blank=True, max_length=64)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_activities', to='organizations.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='leads.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('AUTO_ASSIGNED', 'Auto assigned'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignment_history', to='organizations.employeeprofile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_assignments', to='organizations.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_history', to='leads.lead')),
                ('previous_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_lead_assignments', to='organizations.employeeprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LeadAssignmentCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lead_assignment_cursor', to='organizations.company')),
                ('last_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assignment_cursors', to='organizations.employeeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('META_LEAD_AD', 'Meta lead ad'), ('WEBSITE', 'Website'), ('MANUAL', 'Manual'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], max_length=20)),
                ('external_lead_id', models.CharField(blank=True, max_length=255)),
                ('external_contact_id', models.CharField(blank=True, max_length=255)),
                ('external_conversation_id', models.CharField(blank=True, max_length=255)),
                ('source_details', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_sources', to='organizations.company')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='leads.lead')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'normalized_phone'], name='leads_lead_company_a30a74_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'status', 'created_at'], name='leads_lead_company_bae5d6_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'assigned_to', 'created_at'], name='leads_lead_company_73098e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'source', 'created_at'], name='leads_lead_company_eda25b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company', 'branch', 'created_at'], name='leads_lead_company_7166fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('normalized_phone', ''), _negated=True), fields=('company', 'normalized_phone'), name='unique_lead_phone_per_company'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('budget_minimum__isnull', True), ('budget_maximum__isnull', True), ('budget_minimum__lte', models.F('budget_maximum')), _connector='OR'), name='lead_budget_range_valid'),
        ),
        migrations.AddIndex(
            model_name='leadactivity',
            index=models.Index(fields=['company', 'lead', 'created_at'], name='leads_leada_company_2a23cf_idx'),
        ),
        migrations.AddIndex(
            model_name='leadassignment',
            index=models.Index(fields=['company', 'lead', 'created_at'], name='leads_leada_company_3da964_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['company', 'lead', 'received_at'], name='leads_leads_company_02f4a6_idx'),
        ),
        migrations.AddIndex(
            model_name='leadsource',
            index=models.Index(fields=['company', 'source', 'external_lead_id'], name='leads_leads_company_ce679f_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadsource',
            constraint=models.UniqueConstraint(condition=models.Q(('external_lead_id', ''), _negated=True), fields=('company', 'source', 'external_lead_id'), name='unique_external_lead_per_company_source'),
        ),
    ]
