# Generated by Django 5.2.17 on 2026-09-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_archived',
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Lead created'), ('SOURCE_RECEIVED', 'Source received'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('STATUS_CHANGED', 'Status changed'), ('TEMPERATURE_CHANGED', 'Temperature changed'), ('FIELD_CHANGED', 'Field changed'), ('NOTE_ADDED', 'Note added'), ('FOLLOW_UP_CREATED', 'Follow-up created'), ('TASK_CREATED', 'Task created')], max_length=24),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='leadassignment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='leadsource',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='leads.lead'),
        ),
    ]
