# Generated by Django 5.2.17 on 2026-10-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_archived_at_remove_lead_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Lead created'), ('SOURCE_RECEIVED', 'Source received'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('STATUS_CHANGED', 'Status changed'), ('TEMPERATURE_CHANGED', 'Temperature changed'), ('FIELD_CHANGED', 'Field changed'), ('NOTE_ADDED', 'Note added'), ('FOLLOW_UP_CREATED', 'Follow-up created'), ('FOLLOW_UP_COMPLETED', 'Follow-up completed'), ('FOLLOW_UP_RESCHEDULED', 'Follow-up rescheduled'), ('FOLLOW_UP_REASSIGNED', 'Follow-up reassigned'), ('TASK_CREATED', 'Task created')], max_length=24),
        ),
    ]
