# Generated by Django 5.2.17 on 2026-10-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_employeeprofile_history_safe_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(max_length=32)),
                ('normalized_phone', models.CharField(max_length=32)),
                ('alternate_phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('property_type', models.CharField(blank=True, max_length=100)),
                ('preferred_location', models.CharField(blank=True, max_length=255)),
                ('budget_minimum', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_maximum', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('bhk', models.CharField(blank=True, max_length=30)),
                ('purpose', models.CharField(blank=True, max_length=100)),
                ('requirement_notes', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('META_LEAD_AD', 'Meta lead ad'), ('WEBSITE', 'Website'), ('MANUAL', 'Manual'), ('REFERRAL', 'Referral'), ('OTHER', 'Other')], default='MANUAL', max_length=20)),
                ('source_details', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='raw_leads', to='organizations.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_leads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company', 'created_at'], name='raw_data_ra_company_68a43d_idx'), models.Index(fields=['company', 'normalized_phone'], name='raw_data_ra_company_38917e_idx'), models.Index(fields=['company', 'preferred_location', 'created_at'], name='raw_data_ra_company_569ae5_idx'), models.Index(fields=['company', 'source', 'created_at'], name='raw_data_ra_company_e94e57_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('normalized_phone', ''), _negated=True), fields=('company', 'normalized_phone'), name='unique_raw_lead_phone_per_company'), models.CheckConstraint(condition=models.Q(('budget_minimum__isnull', True), ('budget_maximum__isnull', True), ('budget_minimum__lte', models.F('budget_maximum')), _connector='OR'), name='raw_lead_budget_range_valid')],
            },
        ),
    ]
