# Generated by Django 5.2.17 on 2026-10-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0006_employeeprofile_history_safe_deletion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("notification_type", models.CharField(choices=[("LEAD_ASSIGNED", "Lead assigned"), ("FOLLOW_UP_ASSIGNED", "Follow-up assigned"), ("TASK_ASSIGNED", "Task assigned"), ("ATTENDANCE", "Attendance"), ("LEAVE_REQUEST", "Leave request"), ("INVENTORY", "Inventory"), ("RAW_DATA", "Raw data"), ("SYSTEM", "System")], max_length=32)),
                ("title", models.CharField(max_length=160)),
                ("body", models.TextField(blank=True)),
                ("href", models.CharField(blank=True, max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("company", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="notifications", to="organizations.company")),
                ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["company", "recipient", "is_read", "created_at"], name="core_notifi_company_ffdc76_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["recipient", "created_at"], name="core_notifi_recipie_4a67cf_idx"),
        ),
    ]
