# Generated by Django 5.2.17 on 2026-10-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LEAD_ASSIGNED', 'Lead assigned'), ('FOLLOW_UP_ASSIGNED', 'Follow-up assigned'), ('FOLLOW_UP_REMINDER', 'Follow-up reminder'), ('TASK_ASSIGNED', 'Task assigned'), ('ATTENDANCE', 'Attendance'), ('LEAVE_REQUEST', 'Leave request'), ('INVENTORY', 'Inventory'), ('RAW_DATA', 'Raw data'), ('SYSTEM', 'System')], max_length=32),
        ),
    ]
