# Generated by Django 5.2.17 on 2026-10-04 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0006_employeeprofile_history_safe_deletion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=255)),
                ('unit_number', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('size_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('floor', models.CharField(max_length=100)),
                ('basic_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('landing', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('HOLD', 'Hold'), ('BOOKED', 'Booked'), ('SOLD', 'Sold'), ('BLOCKED', 'Blocked'), ('RESERVED', 'Reserved')], default='AVAILABLE', max_length=16)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='organizations.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['company', 'status', 'created_at'], name='inventory_i_company_f05485_idx'), models.Index(fields=['company', 'project', 'unit_number'], name='inventory_i_company_f15cd1_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'project', 'unit_number'), name='unique_inventory_unit_per_project_company')],
            },
        ),
    ]
