# Generated by Django 5.2.17 on 2026-09-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_remove_lead_archived_at_remove_lead_is_archived_and_more'),
        ('organizations', '0004_employeeprofile_can_receive_leads'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook Lead Ads'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website')], max_length=20)),
                ('external_account_id', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('NOT_CONNECTED', 'Not connected'), ('CONFIGURED', 'Configured'), ('ERROR', 'Error')], default='NOT_CONNECTED', max_length=20)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='integration_configurations', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_configurations', to='organizations.company')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('FACEBOOK', 'Facebook Lead Ads'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website')], max_length=20)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('external_event_id', models.CharField(blank=True, max_length=255)),
                ('external_lead_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=128)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('IGNORED', 'Ignored')], default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_events', to='organizations.company')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='integrations.integrationconfiguration')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_events', to='leads.lead')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationconfiguration',
            index=models.Index(fields=['company', 'provider', 'is_enabled'], name='integration_company_7a1d87_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationconfiguration',
            constraint=models.UniqueConstraint(fields=('provider', 'external_account_id'), name='unique_integration_provider_account'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['company', 'provider', 'status', 'received_at'], name='integration_company_972f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['configuration', 'received_at'], name='integration_configu_7c7394_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.UniqueConstraint(fields=('company', 'provider', 'idempotency_key'), name='unique_integration_event_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('external_event_id', ''), _negated=True), fields=('company', 'provider', 'external_event_id'), name='unique_integration_external_event'),
        ),
    ]
