export type Role = "CEO" | "MANAGER" | "EMPLOYEE";
export interface User { id: number; username: string; email: string; role: Role; }
export type NotificationType = "LEAD_ASSIGNED" | "FOLLOW_UP_ASSIGNED" | "FOLLOW_UP_REMINDER" | "TASK_ASSIGNED" | "ATTENDANCE" | "LEAVE_REQUEST" | "INVENTORY" | "RAW_DATA" | "SYSTEM";
export interface Notification { id: number; notification_type: NotificationType; title: string; body: string; href: string; metadata: Record<string, unknown>; is_read: boolean; read_at: string | null; created_at: string; }
export interface EmployeeProfile { id: number; username: string; full_name: string; email: string; role: Role; branch: number; branch_name: string; department: number; department_name: string; employee_code: string; phone: string; profile_photo: string; designation: string; team: string; personal_address: string; joining_date: string | null; reporting_manager: number | null; reporting_manager_name: string; is_active: boolean; employment_status: "ONBOARDING" | "ACTIVE" | "NOTICE_PERIOD" | "INACTIVE" | "OFFBOARDED"; last_working_date: string | null; }
export interface EmployeeOverview { employee: EmployeeProfile; kpis: Record<string, number | string>; }
export interface MonthlyMetric { month: string; label: string; value: number; }
export interface EmployeePerformance { period: { start: string; end: string }; leads: Record<string, number>; tasks: Record<string, number>; follow_ups: Record<string, number>; attendance: Record<string, number>; site_visits: Record<string, number>; communication: Record<string, number>; lead_distribution: Array<{ label: string; value: number }>; monthly: { leads: MonthlyMetric[]; follow_ups: MonthlyMetric[]; closings: MonthlyMetric[] }; }
export interface LiveLocation { status: "live" | "unavailable"; reason?: "offline" | "stale" | "permission_denied" | "position_unavailable" | "timeout" | "missing_coordinates"; latitude?: number; longitude?: number; accuracy?: number; updated_at?: string; attendance?: "checked_in"; }
export interface LeaveType { id: number; name: string; description: string; annual_allocation: string; allows_negative_balance: boolean; is_active: boolean; }
export interface LeaveRequest { id: number; employee: number; employee_name: string; leave_type: number; leave_type_name: string; start_date: string; end_date: string; number_of_days: string; reason: string; status: "PENDING" | "APPROVED" | "REJECTED" | "CANCELLED"; review_comment: string; created_at: string; }
export interface LeaveBalance { id: number; employee: number; employee_name: string; employee_code: string; leave_type: number; leave_type_name: string; remaining_days: string; used_days: string; updated_at: string; }
export interface Holiday { id: number; branch: number | null; name: string; holiday_date: string; description: string; is_active: boolean; }
export interface EmployeeDocument { id: number; employee: number; employee_name: string; employee_code: string; kind: string; title: string; created_at: string; }
export interface AttendanceWorkspace { date: string; scope: "company" | "team" | "personal"; total_active: number; counts: { present: number; late: number; absent: number; on_leave: number; working_now: number }; records: Array<{ id: number | null; employee: number; employee_name: string; employee_code: string; branch: number; check_in_at: string | null; check_out_at: string | null; total_work_minutes: number; early_checkout: boolean; status: "PRESENT" | "LATE" | "ABSENT" | "ON_LEAVE" | "WORKING_NOW" }> }
export interface HRDashboard { scope: "company" | "team"; kpis: Record<string, number>; attendance: { present: number; late: number; absent: number; on_leave: number; working_now: number; percentage: number; trend: Array<{ date: string; present: number; late: number; absent: number; on_leave: number }> }; leave: { pending: number; approved: number; rejected: number; on_leave_today: number; upcoming: Array<{ id: number; employee__user__username: string; leave_type__name: string; start_date: string; end_date: string }> }; distribution: { departments: Array<{ department__name: string; count: number }>; branches: Array<{ branch__name: string; count: number }>; teams: Array<{ team: string; count: number }> }; holidays: Array<{ id: number; name: string; holiday_date: string; description: string }>; documents: { total: number; recent: Array<{ id: number; title: string; kind: string; created_at: string; employee__user__username: string; employee__employee_code: string }> }; activity: Array<{ id: number; action: string; actor: string; created_at: string; reason: string }>; workforce_activity: Array<{ employee_id: number; employee_name: string; status: "CHECKED_IN" | "CHECKED_OUT" | "NOT_CHECKED_IN"; check_in_at: string | null; attendance_status: "PRESENT" | "LATE" | null }>; performance: { leaderboard: Array<{ employee_id: number; employee_name: string; leads_assigned: number; leads_contacted: number; site_visits: number; closings: number; follow_ups_completed: number; conversion_rate: number }> }; }
export interface EmployeeWork { tasks: Task[]; follow_ups: FollowUp[]; }
export interface Tokens { access: string; refresh: string; }
export interface AttendanceRecord { id: number; employee: number; employee_code: string; employee_name: string; branch: number; attendance_date: string; check_in_at: string | null; check_out_at: string | null; status: "PRESENT" | "LATE"; late_minutes: number; total_work_minutes: number; early_checkout: boolean; corrected_at: string | null; }
export interface NotCheckedIn { status: "NOT_CHECKED_IN"; }
export type CurrentAttendance = AttendanceRecord | NotCheckedIn;
export interface Paginated<T> { count: number; next: string | null; previous: string | null; results: T[]; }
export class ApiError extends Error { constructor(message: string, public status: number, public data?: unknown) { super(message); this.name = "ApiError"; } }
export type WorkPriority = "LOW" | "MEDIUM" | "HIGH" | "URGENT";
export type FollowUpStatus = "PENDING" | "IN_PROGRESS" | "COMPLETED" | "POSTPONED" | "CANCELLED" | "MISSED";
export type TaskStatus = "TODO" | "IN_PROGRESS" | "BLOCKED" | "COMPLETED" | "CANCELLED";
export interface EmployeeReference { id: number; employee_code: string; username: string; display_name?: string; }
export interface EmployeeOption extends EmployeeReference { is_active: boolean; }
export interface FollowUp { id: number; branch: number; assigned_to: number; assigned_to_detail: EmployeeReference; created_by: number; created_by_name: string; lead: number | null; lead_name: string; lead_phone: string; follow_up_type: "CALL" | "WHATSAPP" | "EMAIL" | "SITE_VISIT" | "MEETING" | "OTHER"; title: string; description: string; scheduled_at: string; status: FollowUpStatus; priority: WorkPriority; completed_at: string | null; created_at: string; updated_at: string; }
export interface FollowUpActivity { id: number; performed_by: number; performed_by_name: string; previous_status: string; new_status: string; previous_scheduled_at: string | null; new_scheduled_at: string | null; note: string; activity_type: string; created_at: string; }
export interface Task { id: number; branch: number; title: string; description: string; assigned_to: number; assigned_to_detail: EmployeeReference; created_by: number; created_by_name: string; related_follow_up: number | null; due_date: string; due_time: string | null; priority: WorkPriority; status: TaskStatus; completed_at: string | null; created_at: string; updated_at: string; }
export interface WorkspaceSummary { scope: "company" | "team" | "personal"; follow_ups: { today: number; pending: number; completed: number; upcoming: number; overdue: number; }; tasks: { assigned: number; due_today: number; overdue: number; completed: number; }; }
export interface ReminderPreference { upcoming_follow_up_reminders_enabled: boolean; overdue_follow_up_reminders_enabled: boolean; overdue_task_reminders_enabled: boolean; reminder_lead_minutes: number; daily_summary_enabled: boolean; created_at: string; updated_at: string; }
export type LeadSourceKind = "WHATSAPP" | "FACEBOOK" | "INSTAGRAM" | "META_LEAD_AD" | "WEBSITE" | "MANUAL" | "REFERRAL" | "OTHER";
export type LeadStatus = "NEW" | "CONTACTED" | "SITE_VISIT_REQUESTED" | "SITE_VISIT_DONE" | "FOLLOW_UP_NEEDED" | "FOLLOW_UP_DONE" | "POSTPONED" | "DIFFERENT_REQUIREMENT" | "NOT_INTERESTED" | "CLOSED" | "INVALID_PHONE" | "NOT_LOOKING_PROPERTY" | "USER_IS_AGENT";
export type LeadTemperature = "HOT" | "WARM" | "COLD";
export interface Lead { id: number; branch: number; assigned_to: number | null; assigned_to_detail: EmployeeReference | null; created_by: number | null; created_by_name: string; name: string; phone: string; alternate_phone: string; email: string; property_type: string; preferred_location: string; budget_minimum: string | null; budget_maximum: string | null; bhk: string; purpose: string; requirement_notes: string; source: LeadSourceKind; source_details: string; status: LeadStatus; temperature: LeadTemperature; created_at: string; updated_at: string; }
export interface LeadSummary { scope: "company" | "team" | "personal"; total: number; new: number; contacted: number; hot: number; follow_up_needed: number; site_visits: number; closed: number; }
export interface LeadActivity { id: number; activity_type: string; field_name: string; old_value: string; new_value: string; note: string; metadata: Record<string, unknown>; performed_by: number | null; performed_by_name: string; created_at: string; }
export interface LeadSource { id: number; source: LeadSourceKind; external_lead_id: string; external_contact_id: string; external_conversation_id: string; source_details: string; metadata: Record<string, unknown>; received_at: string; created_at: string; }
export interface LeadAssignment { id: number; previous_assignee: number | null; previous_assignee_detail: EmployeeReference | null; assigned_to: number; assigned_to_detail: EmployeeReference; assigned_by: number | null; assigned_by_name: string; assignment_type: string; reason: string; created_at: string; }
export interface RawLead { id: number; name: string; phone: string; alternate_phone: string; email: string; property_type: string; preferred_location: string; budget_minimum: string | null; budget_maximum: string | null; bhk: string; purpose: string; requirement_notes: string; source: LeadSourceKind; source_details: string; created_at: string; updated_at: string; }
export interface RawDataSummary { total: number; available: number; }
export interface RawPreviewRow { row_number: number; valid: boolean; errors: string[]; normalized_phone?: string; name: string; phone: string; alternate_phone: string; email: string; property_type: string; preferred_location: string; budget_minimum: string; budget_maximum: string; bhk: string; purpose: string; requirement_notes: string; source: LeadSourceKind; source_details: string; }
export interface RawPreview { rows: RawPreviewRow[]; summary: { total: number; valid: number; invalid: number; duplicates: number; }; }
export interface RawEligibleEmployee { id: number; username: string; employee_code: string; branch: number; }
export interface RawDistributionPreview { raw_lead_ids: number[]; total: number; mode: "EQUAL" | "SPECIFIC" | "CUSTOM"; allocations: Array<{ employee_id: number; employee_name: string; count: number }>; }
export type InventoryStatus = "AVAILABLE" | "HOLD" | "BOOKED" | "SOLD" | "BLOCKED" | "RESERVED";
export interface InventoryItem { id: number; project: string; unit_number: string; property_type: string; size_sqft: string; floor: string; basic_price: string; landing?: string | null; status: InventoryStatus; booking_date: string | null; created_at: string; updated_at: string; }
export interface InventorySummary { total: number; available: number; hold: number; booked: number; sold: number; landing_total?: string; }
export type IntegrationProvider = "WHATSAPP" | "FACEBOOK" | "INSTAGRAM" | "WEBSITE";
export interface IntegrationConfiguration { id: number; provider: IntegrationProvider; branch: number; external_account_id: string; is_enabled: boolean; status: "NOT_CONNECTED" | "CONFIGURED" | "ERROR"; secret_configured: boolean; last_success_at: string | null; last_failure_at: string | null; last_failure_message: string; failed_event_count: number; created_at: string; updated_at: string; }
export interface IntegrationEvent { id: number; provider: IntegrationProvider; event_type: string; external_event_id: string; external_lead_id: string; lead_id: number | null; status: string; received_at: string; processed_at: string | null; retry_count: number; error_message: string; }
