# Generated by Django 5.2.17 on 2026-09-25 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_employeeprofile_reporting_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('CALL', 'Call'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SITE_VISIT', 'Site visit'), ('MEETING', 'Meeting'), ('OTHER', 'Other')], default='CALL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_follow_ups', to='organizations.employeeprofile')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_ups', to='organizations.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], max_length=20)),
                ('new_status', models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], max_length=20)),
                ('previous_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('new_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status changed'), ('POSTPONED', 'Postponed'), ('REASSIGNED', 'Reassigned'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NOTE_ADDED', 'Note added')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_activities', to='organizations.company')),
                ('follow_up', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='workspace.followup')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upcoming_follow_up_reminders_enabled', models.BooleanField(default=True)),
                ('overdue_task_reminders_enabled', models.BooleanField(default=True)),
                ('reminder_lead_minutes', models.PositiveIntegerField(default=30)),
                ('daily_summary_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder_preferences', to='organizations.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('TODO', 'To do'), ('IN_PROGRESS', 'In progress'), ('BLOCKED', 'Blocked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='TODO', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to='organizations.employeeprofile')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='organizations.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='organizations.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='workspace.followup')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('UPCOMING_FOLLOW_UP', 'Upcoming follow-up'), ('OVERDUE_TASK', 'Overdue task')], max_length=32)),
                ('source_key', models.CharField(max_length=160)),
                ('scheduled_for', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder_events', to='organizations.company')),
                ('follow_up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_events', to='workspace.followup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_events', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminder_events', to='workspace.task')),
            ],
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['company', 'assigned_to', 'scheduled_at'], name='workspace_f_company_0e69b6_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['company', 'status', 'scheduled_at'], name='workspace_f_company_79ccb6_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['company', 'priority'], name='workspace_f_company_11a265_idx'),
        ),
        migrations.AddConstraint(
            model_name='followup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='followup_completion_timestamp_consistent'),
        ),
        migrations.AddIndex(
            model_name='followupactivity',
            index=models.Index(fields=['company', 'follow_up', 'created_at'], name='workspace_f_company_853f76_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminderpreference',
            constraint=models.UniqueConstraint(fields=('company', 'user'), name='unique_reminder_preference_per_user_company'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'assigned_to', 'due_date'], name='workspace_t_company_c5801e_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'status', 'due_date'], name='workspace_t_company_9d632f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['company', 'priority'], name='workspace_t_company_6c01c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'COMPLETED')), models.Q(models.Q(('status', 'COMPLETED'), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='task_completion_timestamp_consistent'),
        ),
        migrations.AddIndex(
            model_name='reminderevent',
            index=models.Index(fields=['company', 'user', 'scheduled_for'], name='workspace_r_company_d0b630_idx'),
        ),
        migrations.AddConstraint(
            model_name='reminderevent',
            constraint=models.UniqueConstraint(fields=('company', 'user', 'source_key'), name='unique_prepared_reminder_event'),
        ),
        migrations.AddConstraint(
            model_name='reminderevent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('follow_up__isnull', False), ('task__isnull', True)), models.Q(('follow_up__isnull', True), ('task__isnull', False)), _connector='OR'), name='reminder_event_has_exactly_one_source'),
        ),
    ]
