# Generated by Django 5.2.17 on 2026-09-27 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_lead_archived_at_remove_lead_is_archived_and_more'),
        ('workspace', '0002_followup_lead_task_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='leads.lead'),
        ),
    ]
