# Generated by Django 5.2.17 on 2026-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_followup_lead_alter_task_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT_REQUESTED', 'Site Visit Requested'), ('SITE_VISIT_DONE', 'Site Visit Done'), ('FOLLOW_UP_NEEDED', 'Follow Up Needed'), ('FOLLOW_UP_DONE', 'Follow Up Done'), ('POSTPONED', 'Postponed'), ('DIFFERENT_REQUIREMENT', 'Different Requirement'), ('NOT_INTERESTED', 'Not Interested'), ('CLOSED', 'Closed'), ('INVALID_PHONE', 'Invalid Phone'), ('NOT_LOOKING_PROPERTY', 'Not Looking Property'), ('USER_IS_AGENT', 'User Is Agent'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], default='NEW', max_length=32),
        ),
        migrations.AlterField(
            model_name='followupactivity',
            name='new_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT_REQUESTED', 'Site Visit Requested'), ('SITE_VISIT_DONE', 'Site Visit Done'), ('FOLLOW_UP_NEEDED', 'Follow Up Needed'), ('FOLLOW_UP_DONE', 'Follow Up Done'), ('POSTPONED', 'Postponed'), ('DIFFERENT_REQUIREMENT', 'Different Requirement'), ('NOT_INTERESTED', 'Not Interested'), ('CLOSED', 'Closed'), ('INVALID_PHONE', 'Invalid Phone'), ('NOT_LOOKING_PROPERTY', 'Not Looking Property'), ('USER_IS_AGENT', 'User Is Agent'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='followupactivity',
            name='previous_status',
            field=models.CharField(blank=True, choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('SITE_VISIT_REQUESTED', 'Site Visit Requested'), ('SITE_VISIT_DONE', 'Site Visit Done'), ('FOLLOW_UP_NEEDED', 'Follow Up Needed'), ('FOLLOW_UP_DONE', 'Follow Up Done'), ('POSTPONED', 'Postponed'), ('DIFFERENT_REQUIREMENT', 'Different Requirement'), ('NOT_INTERESTED', 'Not Interested'), ('CLOSED', 'Closed'), ('INVALID_PHONE', 'Invalid Phone'), ('NOT_LOOKING_PROPERTY', 'Not Looking Property'), ('USER_IS_AGENT', 'User Is Agent'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('MISSED', 'Missed')], max_length=32),
        ),
    ]
