# Generated by Django 5.2.17 on 2026-09-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_employeeprofile_reporting_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='can_receive_leads',
            field=models.BooleanField(default=True),
        ),
    ]
