# Generated by Django 5.2.17 on 2026-09-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_employeeprofile_can_receive_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='employment_status',
            field=models.CharField(choices=[('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('NOTICE_PERIOD', 'Notice period'), ('INACTIVE', 'Inactive'), ('OFFBOARDED', 'Offboarded')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_working_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='offboarding_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='personal_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to='employee-profile-photos/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='team',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
