# Generated by Django 5.2.17 on 2026-10-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("organizations", "0005_employeeprofile_designation_and_more")]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
